---
:concurrency: 5
production:
  :concurrency: <%= ENV.fetch("RAILS_SIDEKIQ_CONCURRENCY") { 1 } %>
:queues:
  - low
  - high
:limits:
  connect_lab: 2
:scheduler:
  :schedule:
    import_users_worker:
      class: ImportUsersWorker
      cron: '0 * * * * *'   # Runs once per minute